usedFog = list()
unusedFog = list()
requestList1=dict()
requestList2=dict()
requestList=dict()
distanceMap=dict()
listOfDevices=[]
listOfFogNodes=[]
handshake_times = []
workloadtimes = []
requesttimes=[]
fogcounter=int()
fifo_times=[]
da_times=[]
dqn_times=[]
actionspace = 0
edge_list = []
fog_list=[]